### ISSUE TITLE
inject stack outputs to script?

### ISSUE THREAD

**Issue by tommedema** [mvila/serverless-plugin-scripts#1]
how would you inject the output of your cloudformation stack, e.g. `ServiceEndpoint`, to a build script for post processing? e.g. to dynamically inject the api endpoint into your frontend

**Comment by mvila** [comment]
I think you can do that using variables:

https://serverless.com/framework/docs/providers/aws/guide/variables/

**Comment by tommedema** [comment]
@mvila I thought so too but failed to achieve the desired result

**Comment by tommedema** [comment]
Ultimately I did it like so:

_serverless.yml_

```
custom:
  
  scriptHooks:
    after:aws:info:gatherData: scripts/compile-web.js
```

_compile-web.js_

```
/* global serverless */

console.log('compiling web package with cloudformation outputs')

const awsInfo = serverless.pluginManager.plugins.find(p => p.constructor.name === 'AwsInfo')
const getOutput = key => awsInfo.gatheredData.outputs.find(o => o.OutputKey === key).OutputValue
const gatewayUrl = getOutput('ServiceEndpoint')
console.log(gatewayUrl)
```

Note that this is using https://github.com/weixu365/serverless-scriptable-plugin

Seems rather hackish though.

**Comment by mvila** [comment]
I agree, it doesn't look very clean. I am sorry but I am afraid I cannot help you more on that. Actually, I stopped using Serverless Framework...
