### ISSUE TITLE
Lifecycle Events Documentation

### ISSUE THREAD

**Issue by x11joe** [mvila/serverless-plugin-scripts#2]
I went to the serverless website but can't seem to find the documentation for the different life cycle events.  Do you know what the event is for after a resource is created in serverless, like say an RDS Database Instance etc or S3 Bucket.  I want to run the script after those have been confirmed to be created successfully.

**Comment by mvila** [comment]
Apparently, this information has disappeared from the official documentation. I did a quick search, and the best I could find is:

https://gist.github.com/HyperBrain/50d38027a8f57778d5b0f135d80ea406

**Comment by x11joe** [comment]
Thanks for finding that, that for sure helps!

**Comment by x11joe** [comment]
Do you know the event for after its done updating the resources in cloud formation? I can't figure it out from the link you gave.  I tried deploy:finalize but it never runs any scripts.
