### ISSUE TITLE
Commands no longer working with SLS v1.59.2

### ISSUE THREAD

**Issue by mikestopcontinues** [mvila/serverless-plugin-scripts#8]
I took the example right out of the docs, and I get:

> Serverless command "hello" not found. Did you mean "deploy"? Run "serverless help" for a list of all available commands.

Thanks!

**Comment by mvila** [comment]
Hi @mikestopcontinues,

I am so sorry, but I am currently super busy and I don't use the Serverless framework so much anymore.

However, PRs welcome!

**Comment by syl20lego** [comment]
I'm using 1.63.0 and don't see any issue

**Comment by mikestopcontinues** [comment]
I no longer use SLS, so I'm going to close this.
