### ISSUE TITLE
Feature request: Add ability to specify script configuration with variables

### ISSUE THREAD

**Issue by Enase** [mvila/serverless-plugin-scripts#9]
Add ability to specify `script` configuration node as any [sls variable](https://www.serverless.com/framework/docs/providers/aws/guide/variables/).

*Example:*
```
custom:
  scripts: ${file(./your/path/config-hooks.yml)}
```

*Proposal:*
Add configuration value population in configuration load method `getConfig()`

[Current state](https://github.com/mvila/serverless-plugin-scripts/blob/master/src/index.js#L15):
```
  getConfig() {
    const service = this.serverless.service;
    return service.custom && service.custom.scripts;
  }
```

Change proposition:
```
  getConfig() {
    const service = this.serverless.service;
    const config = service.custom && service.custom.scripts;
    if (config) {
       return this.serverless.variables.populateValue(config);
    }
    return undefined;
  }
```

**Comment by mvila** [comment]
I am so sorry, but since I don't use the Serverless framework anymore, I don't feel comfortable adding new features. I edited the README to mention that this project is now in maintenance mode.
